# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RoIM22UuZHL_7cxR4IepCG6w1b5w8SC-
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ================== CSS ==================
st.markdown("""
<style>

/* ซ่อน anchor */
h1 a, h2 a, h3 a, h4 a {
    display: none !important;
}

/* ===== LIGHT MODE ONLY ===== */
@media (prefers-color-scheme: light) {

    /* พื้นหลังเว็บ */
    body, .stApp {
        background-color: #f5f6e5;
    }

    /* หัวข้อ */
    h1 {
        color: #759b69 !important;
        font-family: 'Puimek', sans-serif;
    }

    /* label + text */
    label, .stMarkdown, .stText {
        color: #000000 !important;
    }

    /* slider bar */
    .stSlider > div > div {
        color: #759b69 !important;
    }

    /* slider track */
    .stSlider [data-baseweb="slider"] div {
        background-color: #759b69 !important;
    }

    /* RESULT BOX (แนะนำให้ปลูก) */
    .result-box {
        background-color: #b0c663;
        color: #000000;
        padding: 20px;
        border-radius: 15px;
        text-align: center;
    }

    /* OTHER CHOICE BOX */
    .other-box {
        background-color: #759b69;
        color: #ffffff;
        padding: 10px;
        margin: 5px;
        border-radius: 10px;
    }

    /* chart background */
    .stPlotlyChart, .stBarChart {
        background-color: #f5f6e5 !important;
    }
}

</style>
""", unsafe_allow_html=True)

# ================== LOAD MODEL ==================
rf_model = joblib.load("rf_model.pkl")
xgb_model = joblib.load("xgb_model.pkl")
scaler = joblib.load("scaler.pkl")
le = joblib.load("label_encoder.pkl")

# ================== VALIDATION ==================
def validate_input(data):
    rules = {
        "N": (0, 140),
        "P": (5, 145),
        "K": (5, 205),
        "temperature": (-10, 45),
        "humidity": (10, 100),
        "ph": (3.5, 9),
        "rainfall": (20, 300)
    }

    for col, (min_val, max_val) in rules.items():
        if not (min_val <= data[col] <= max_val):
            return False, f"{col} out of range"

    return True, "OK"

# ================== PREP ==================
def prepare_input(user_dict):
    df = pd.DataFrame([user_dict])
    return scaler.transform(df)

# ================== ENSEMBLE ==================
def ensemble_predict(rf_model, xgb_model, sample, le, w_rf=0.4, w_xgb=0.6):
    rf_probs = rf_model.predict_proba(sample)[0]
    xgb_probs = xgb_model.predict_proba(sample)[0]

    combined = (w_rf * rf_probs) + (w_xgb * xgb_probs)
    top3_idx = combined.argsort()[-3:][::-1]

    results = []
    for i in top3_idx:
        crop = le.inverse_transform([i])[0]
        percent = combined[i] * 100
        results.append((crop, percent))

    best_crop = results[0]
    return best_crop, results

# ================== UI ==================
st.set_page_config(page_title="Crop Recommendation", layout="centered")

st.markdown(
    "<h1 style='font-size:40px;'>🌱 Crop Recommendation</h1>",
    unsafe_allow_html=True
)

st.caption("เลือกค่าดิน")

# INPUT
N = st.slider("Nitrogen (N)", 0, 140, 50)
P = st.slider("Phosphorus (P)", 5, 145, 50)
K = st.slider("Potassium (K)", 5, 205, 50)
temperature = st.slider("Temperature (°C)", -10, 45, 25)
humidity = st.slider("Humidity (%)", 10, 100, 70)
ph = st.slider("pH", 3.5, 9.0, 6.5)
rainfall = st.slider("Rainfall (mm)", 20, 300, 100)

user_input = {
    "N": N,
    "P": P,
    "K": K,
    "temperature": temperature,
    "humidity": humidity,
    "ph": ph,
    "rainfall": rainfall
}

# ================== BUTTON ==================
if st.button("Predict"):

    valid, msg = validate_input(user_input)

    if not valid:
        st.error(f"❌ {msg}")
    else:
        sample = prepare_input(user_input)
        best_crop, top3 = ensemble_predict(rf_model, xgb_model, sample, le)

        st.markdown("<h2>แนะนำให้ปลูก</h2>", unsafe_allow_html=True)

        # RESULT
        st.markdown(
            f"""
            <div class="result-box">
                <h1>{best_crop[0]}</h1>
                <h2>{best_crop[1]:.1f}%</h2>
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown("<h3>Other choice</h3>", unsafe_allow_html=True)

        # TOP 3
        for crop, percent in top3:
            st.markdown(
                f"""
                <div class="other-box">
                    <b>{crop}</b>
                    <span style="float:right;">{percent:.1f}%</span>
                </div>
                """,
                unsafe_allow_html=True
            )

        # CHART
        df_chart = pd.DataFrame(top3, columns=["Crop", "Percent"])
        st.bar_chart(df_chart.set_index("Crop"))

